#!/bin/bash

set -e

docker run --rm -d -e ISC_PASSWORD=nix -e FIREBIRD_DATABASE=sqitchtest.db -p 3050:3050 jacobalberty/firebird:${FIREBIRD:=latest}
sudo add-apt-repository -y ppa:mapopa/firebird3.0
sudo apt-get update -qq
sudo apt-get install -qq firebird-dev firebird3.0-utils
sleep 10
echo 'quit;' | isql-fb -sqldialect 3 -charset UTF8 -user sysdba -password nix 0.0.0.0:/firebird/data/sqitchtest.db
export FIREBIRD_URI=db:firebird://sysdba:nix@0.0.0.0//firebird/data/sqitchtest.db
